server:
  port: 8080

project:
  name: leads-website
  version: 1.0
  description: something something something

logging:
  org.hibernate: INFO

vaadin:
  productionMode: false
  async-supported: true

spring:
  security:
    oauth2:
      client:
        registration:
#          microsoft:
#            # todo:
#            clientId: "c8e3f736-b2a9-4896-82fb-5097b7a16a6a"
#            clientSecret: "jH17Q~uG0QcImmDVvrSKYMzcb5.WH1pnKC_Iv"
#            clientName: "Azure"
#            provider: "azure"
          google:
            clientId: "51527637151-ve222nql8vd8t5biedb4ermm42de95bd.apps.googleusercontent.com"
            clientSecret: "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"
          facebook:
            clientId: "3210071899317932"
            clientSecret: "79c2268ddefa9764631b49b4cedb029d"
            scope:
              - email
              - public_profile
#          discord:
#            clientId: "962150567524831232"
#            clientSecret: "CtKl_ACq78BXp--cjA6ktGxNWGq1sv2a"
#            clientAuthenticationMethod: post
#            authorizationGrantType: authorization_code
#            redirect-uri-template: "{baseUrl}/login/oauth2/code/discord"
#            scope:
#              - "email"
#              - "identify"
#          github:
#            clientId: "0afc9bf38b0dac9cd8f7"
#            clientSecret: "e4a38218ccb49f50b1647cc7b67c671787fd50ec"
#            scope:
#              - "user"
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            usernameAttribute: username
