server:
  port: 8080

project:
  name: leads-website
  version: 1.0
  description: something something something

logging:
  file: runtime_prod.log
  org.hibernate: INFO

vaadin:
  productionMode: true

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ""
            clientSecret: ""
