server:
  port: 8080

project:
  name: leads-website
  version: 1.0
  description: something something something

logging:
  org.hibernate: INFO

vaadin:
  productionMode: false
  async-supported: true

spring:
  security:
    oauth2:
      client:
        registration:
          twitter:
            clientId: Q19mdnc1VHRTc2JuSXlIMUIwcVM6MTpjaQ
            clientSecret: zmCTUkhAG7StJGbwkv6LsviVLE3gv86jZXmgmTLEY5e-83vET_
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/twitter"
          google:
            clientId: "51527637151-ve222nql8vd8t5biedb4ermm42de95bd.apps.googleusercontent.com"
            clientSecret: "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"
          discord:
            clientId: "962150567524831232"
            clientSecret: "CtKl_ACq78BXp--cjA6ktGxNWGq1sv2a"
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/discord"
            scope:
              - "email"
              - "identify"
          microsoft:
            client-id: c8e3f736-b2a9-4896-82fb-5097b7a16a6a
            client-secret: KoX7Q~-BzXbNibSRTQbiGRxDU6hYz4BBTlflA
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/microsoft'
            scope:
              - "User.Read"
            client-name: Microsoft
          facebook:
            clientId: "3210071899317932"
            clientSecret: "79c2268ddefa9764631b49b4cedb029d"
            scope:
              - "email"
              - "public_profile"
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/authorize?resource=https://graph.microsoft.com/
            token-uri: https://login.microsoftonline.com/common/oauth2/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
            user-name-attribute: sub
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/keys
          twitter:
            authorizationUri: https://api.twitter.com/oauth/authorize
            tokenUri: https://api.twitter.com/oauth/access_token
            userInfoUri: https://api.twitter.com/1.1/users/show.json
            userNameAttribute: screen_name
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discordapp.com/api/users/@me
            userNameAttribute: username
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
