server:
  port: 8080

password:
  test: "Gz5*jqD^p/X[j23R(-%n7,,+$d;8kU"

project:
  name: leads-website
  version: 1.0
  description: something something something

logging:
  file: runtime_prod.log
  org.hibernate: INFO

vaadin:
  productionMode: true
